service: cadastro-pacientes

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: dev
  region: us-west-2

functions:
  listarPacientes:
    handler: handler.listarPacientes
 # linhas responsaveis, para publicar apigateway dentro da stack 
    events: 
      - http:
          path: pacientes
          method: get 
  obterPacientes:
    handler: handler.obterPacientes
    events: 
      - http:
          path: pacientes/{pacienteId}
          method: get 

